[package]
name = "esp-bluedroid-logger"
version = "0.1.0"
edition = "2024"

[dependencies]
esp-bluedroid = { path = "../.." }
serde = "1.0.219"
log = "0.4"
anyhow = "1.0.97"
ringbuf = "0.4.8"
crossbeam = "0.8.4"
lazy_static = "1.5.0"
